/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    magazines: Magazine;
    hospitals: Hospital;
    doctors: Doctor;
    departments: Department;
    regions: Region;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    magazines: MagazinesSelect<false> | MagazinesSelect<true>;
    hospitals: HospitalsSelect<false> | HospitalsSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazines".
 */
export interface Magazine {
  id: number;
  slug: string;
  type: 'article' | 'qna' | 'regional' | 'interview' | 'case';
  seoTitle: string;
  metaDescription: string;
  /**
   * AEO용 핵심 답변 (요약 박스에 노출)
   */
  shortAnswer: string;
  /**
   * 본문 (마크다운). ## 제목, **Q. 질문**, - 리스트, | 표 형식 지원.
   */
  body: string;
  /**
   * 타겟 키워드 (여러 개 입력)
   */
  targetKeywords?: string[] | null;
  faqBlocks?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  priceTable?:
    | {
        treatment: string;
        priceRange: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 연결할 병원
   */
  linkedHospitals?: (number | Hospital)[] | null;
  /**
   * 연결 진료과
   */
  linkedDepartment?: (number | null) | Department;
  /**
   * 연결 지역
   */
  linkedRegion?: (number | null) | Region;
  /**
   * 의사 저자. 설정 시 저자 프로필 + 의원 cross-link 자동 노출.
   */
  authorDoctor?: (number | null) | Doctor;
  /**
   * 연결 시술 slug (시술 컬렉션 도입 전까지 텍스트 유지)
   */
  linkedTreatmentSlug?: string | null;
  /**
   * authorDoctor 미설정 시 사용 (큐레이션팀/외부 전문가).
   */
  authorName?: string | null;
  authorTitle?: string | null;
  /**
   * ★ 의료법 광고심의 안전 문구 자동 주입. 매거진 푸터에 자동 표시.
   */
  disclaimerType: 'general' | 'case' | 'price' | 'qna';
  publishedAt: string;
  /**
   * 미입력 시 타입에서 자동 설정.
   */
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals".
 */
export interface Hospital {
  id: number;
  slug: string;
  nameKr: string;
  shortDescription?: string | null;
  /**
   * 진료과 참조
   */
  department: number | Department;
  /**
   * 최하위 지역 참조 (동이 있으면 동, 없으면 시군구). 상위 지역은 region.parent 체인으로 해석
   */
  region: number | Region;
  addressLine: string;
  nearestStation?: string | null;
  /**
   * 가장 가까운 지하철역명 (역주변 필터용, 예: 아라역)
   */
  nearestStationName?: string | null;
  walkingMinutes?: number | null;
  tier: 'STANDARD' | 'PREMIUM' | 'HERITAGE';
  phone?: string | null;
  yearEstablished?: number | null;
  rating: number;
  reviewCount: number;
  doctorCount: number;
  monthlyVisitors?: number | null;
  /**
   * 태그 (예: 임플란트, 보철)
   */
  tags?: string[] | null;
  certification?: {
    stage1History?: boolean | null;
    stage1Detail?: string | null;
    stage2Reviews?: boolean | null;
    stage2Detail?: string | null;
    stage3Credentials?: boolean | null;
    stage3Detail?: string | null;
    stage4Facility?: boolean | null;
    stage4Detail?: string | null;
    /**
     * 예: 2026-05
     */
    certifiedAt?: string | null;
  };
  curationNote?: {
    text?: string | null;
    curatorName?: string | null;
    curatorTitle?: string | null;
  };
  prices?:
    | {
        treatmentName: string;
        treatmentNote?: string | null;
        normalLow: number;
        normalHigh: number;
        eventLow?: number | null;
        eventHigh?: number | null;
        insuranceNote?: string | null;
        id?: string | null;
      }[]
    | null;
  reviews?:
    | {
        id?: string | null;
        rating?: number | null;
        content?: string | null;
        reviewerName?: string | null;
        visitedAt?: string | null;
        treatmentName?: string | null;
        ageGroup?: string | null;
        isReceiptVerified?: boolean | null;
        isPhoneVerified?: boolean | null;
      }[]
    | null;
  hours?: {
    weekday?: string | null;
    saturday?: string | null;
    sunday?: string | null;
    lunch?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  slug: string;
  nameKr: string;
  nameEn: string;
  nameJp?: string | null;
  /**
   * 齒, 骨, 眼, 診 등
   */
  hanja: string;
  description: string;
  /**
   * 시니어 niche 우선순위 (1=임플란트치과)
   */
  priority: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  slug: string;
  nameKr: string;
  nameEn?: string | null;
  /**
   * 지역 depth (시도 → 시군구 → 동)
   */
  level?: ('sido' | 'sigungu' | 'dong') | null;
  /**
   * 상위 지역 참조. 시/도면 비움.
   */
  parent?: (number | null) | Region;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  slug: string;
  nameKr: string;
  /**
   * 한자 1자 (아바타용)
   */
  nameHanja?: string | null;
  /**
   * 대표원장 / 부원장 등
   */
  title?: string | null;
  yearsExperience?: number | null;
  specialty?: string | null;
  credentials?: string[] | null;
  /**
   * 소속 의원
   */
  hospital?: (number | null) | Hospital;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor' | 'sales' | 'curator') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'magazines';
        value: number | Magazine;
      } | null)
    | ({
        relationTo: 'hospitals';
        value: number | Hospital;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazines_select".
 */
export interface MagazinesSelect<T extends boolean = true> {
  slug?: T;
  type?: T;
  seoTitle?: T;
  metaDescription?: T;
  shortAnswer?: T;
  body?: T;
  targetKeywords?: T;
  faqBlocks?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  priceTable?:
    | T
    | {
        treatment?: T;
        priceRange?: T;
        note?: T;
        id?: T;
      };
  linkedHospitals?: T;
  linkedDepartment?: T;
  linkedRegion?: T;
  authorDoctor?: T;
  linkedTreatmentSlug?: T;
  authorName?: T;
  authorTitle?: T;
  disclaimerType?: T;
  publishedAt?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals_select".
 */
export interface HospitalsSelect<T extends boolean = true> {
  slug?: T;
  nameKr?: T;
  shortDescription?: T;
  department?: T;
  region?: T;
  addressLine?: T;
  nearestStation?: T;
  nearestStationName?: T;
  walkingMinutes?: T;
  tier?: T;
  phone?: T;
  yearEstablished?: T;
  rating?: T;
  reviewCount?: T;
  doctorCount?: T;
  monthlyVisitors?: T;
  tags?: T;
  certification?:
    | T
    | {
        stage1History?: T;
        stage1Detail?: T;
        stage2Reviews?: T;
        stage2Detail?: T;
        stage3Credentials?: T;
        stage3Detail?: T;
        stage4Facility?: T;
        stage4Detail?: T;
        certifiedAt?: T;
      };
  curationNote?:
    | T
    | {
        text?: T;
        curatorName?: T;
        curatorTitle?: T;
      };
  prices?:
    | T
    | {
        treatmentName?: T;
        treatmentNote?: T;
        normalLow?: T;
        normalHigh?: T;
        eventLow?: T;
        eventHigh?: T;
        insuranceNote?: T;
        id?: T;
      };
  reviews?:
    | T
    | {
        id?: T;
        rating?: T;
        content?: T;
        reviewerName?: T;
        visitedAt?: T;
        treatmentName?: T;
        ageGroup?: T;
        isReceiptVerified?: T;
        isPhoneVerified?: T;
      };
  hours?:
    | T
    | {
        weekday?: T;
        saturday?: T;
        sunday?: T;
        lunch?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  slug?: T;
  nameKr?: T;
  nameHanja?: T;
  title?: T;
  yearsExperience?: T;
  specialty?: T;
  credentials?: T;
  hospital?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  slug?: T;
  nameKr?: T;
  nameEn?: T;
  nameJp?: T;
  hanja?: T;
  description?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  slug?: T;
  nameKr?: T;
  nameEn?: T;
  level?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}